[package]
name = "crates_api"
version = "0.1.0"
authors = ["Gustavo Aguiar <gugahoa@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
serde_json = "1.0"

serde = { version = "1.0", features = ["derive"]}
